// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASK2stjBg0HR1wupY_tpzfKecBvZw4mHI',
    appId: '1:437822465539:web:6c3d1225e11e7446d4d036',
    messagingSenderId: '437822465539',
    projectId: 'kitaagro',
    authDomain: 'kitaagro.firebaseapp.com',
    storageBucket: 'kitaagro.firebasestorage.app',
    measurementId: 'G-9VTQX19X5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyvrduQjcCTrknXlscoyTWmnQJ3gcJusI',
    appId: '1:437822465539:android:d17fe281e99b20cdd4d036',
    messagingSenderId: '437822465539',
    projectId: 'kitaagro',
    storageBucket: 'kitaagro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhL9YD2vloArsPFcZvJyQ74zD1ITpXRnk',
    appId: '1:437822465539:ios:c915c70858fec229d4d036',
    messagingSenderId: '437822465539',
    projectId: 'kitaagro',
    storageBucket: 'kitaagro.firebasestorage.app',
    iosBundleId: 'com.example.kitaAgro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhL9YD2vloArsPFcZvJyQ74zD1ITpXRnk',
    appId: '1:437822465539:ios:c915c70858fec229d4d036',
    messagingSenderId: '437822465539',
    projectId: 'kitaagro',
    storageBucket: 'kitaagro.firebasestorage.app',
    iosBundleId: 'com.example.kitaAgro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASK2stjBg0HR1wupY_tpzfKecBvZw4mHI',
    appId: '1:437822465539:web:0a5a21fa63ebc635d4d036',
    messagingSenderId: '437822465539',
    projectId: 'kitaagro',
    authDomain: 'kitaagro.firebaseapp.com',
    storageBucket: 'kitaagro.firebasestorage.app',
    measurementId: 'G-DGF1FFV2T3',
  );
}
